### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by duli1985** [vieyahn2017/duyu#15]
```
#!user/bin/env Python
# -*- coding: utf-8 -*-
import re
import time
import linecache

#BusinessCode业务代码
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认

cfm_Order = 'C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT'
the_file = open(cfm_Order)
content = the_file.read()
order_detail = linecache.getline(cfm_Order, 128)
# order_detail = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|180004|0|20171128|141233|0000|0106A00000055|    379  |    0000000000000000|0000000000100000|122|181010000001|3790000000006       |1|10000|                   |    |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
list = order_detail.strip().split('|')
new_detail = []
AppSheetSerialNo = '541801030000000000237992' #申请订单号
TransactionCfmDate = '20180119' #确认日期
ConfirmedVol = '0000000000888000' #确认份额:16位，2位小数
ConfirmedAmount = '0000000000888000' #确认金额：16位，2位小数
FundCode = '021531' #产品编码，与ta对应
TransactionDate = '20180118' #交易发生日期
TransactionTime = time.strftime('%H%M%S') #交易发生时间：时分秒
ReturnCode = '0000' #交易处理返回结果码：0000代表成功
TransactionAccountID = '0106A00000108' #投资人交易基金账号
ApplicationVol = '    0000000000000000' #申请基金份数16位，前面空格不能省略，基金公司给的文件问题：赎回填此处，申购默认为0
ApplicationAmount = '0000000000888000' #申请金额：申购填此处，赎回默认为0
BusinessCode = '122'
TASerialNO = '3790000000006       ' #TA确认交易流水号:TA交易时用

new_detail.append(AppSheetSerialNo)
new_detail.append(TransactionCfmDate)
new_detail.append(list[2]) #CurrencyType结算币种
new_detail.append(ConfirmedVol)
new_detail.append(ConfirmedAmount)
new_detail.append(FundCode)
new_detail.append(list[6]) #LargeRedemptionFlag巨额赎回标志
new_detail.append(TransactionDate)
new_detail.append(TransactionTime)
new_detail.append(ReturnCode)
new_detail.append(TransactionAccountID)
new_detail.append(list[11]) #DistributorCode销售人代码,379
new_detail.append(ApplicationVol)
new_detail.append(ApplicationAmount)
new_detail.append(CFM_SG)


new_detail = '|'.join(new_detail)

print order_detail
print new_detail
# try:
#     search_date_lines = re.search(r"379\n\d+\n999", content).group()
#     ### 正则搜索379\n20180108\n999 这三行
# except AttributeEror:
#     pass

'''
work_date = "20180110" # 你要改成的日期


# 正则替换379\n20180108\n999 这三行 直接替换，不用先搜索
content = re.sub(r"379\s+\d+\s+999",  "379\n" + work_date + "\n999", content)
# 搜索最后交易记录的那几行
detail_order_lines_se = re.search(r"SHAREREGISTERDATE\n[\s\S]*\nOFDCFEND", content)

if detail_order_lines_se is not None:
    detail_order_lines = detail_order_lines_se.group().split('\n')
    order_counts = len(detail_order_lines) - 3
    #去掉首行SHAREREGISTERDATE  第二行（记录条数） 尾行OFDCFEND
    order_counts_8_bits = str(order_counts).zfill(8)
    content = re.sub(r"SHAREREGISTERDATE\n\d+\n", "SHAREREGISTERDATE\n%s\n" % order_counts_8_bits, content)

print content

f = open(the_file_name.replace(".txt", "__marked.txt"), 'w')
f.write(content)
f.close()
'''
```

**Comment by vieyahn2017** [comment]
```python
#!user/bin/env Python
# -*- coding: utf-8 -*-
import re
import time
import linecache

#BusinessCode业务代码
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认

# cfm_Order = 'C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT'
# the_file = open(cfm_Order)
# content = the_file.read()
# order_detail = linecache.getline(cfm_Order, 128)

order_detail = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|180004|0|20171128|141233|0000|0106A00000055|    379  |    0000000000000000|0000000000100000|122|181010000001|3790000000006       |1|10000|                   |    |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
"""
#方便数，每5个一行
order_detail     = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|
                    180004|0|20171128|141233|0000|
                    0106A00000055|    379  |    0000000000000000|0000000000100000|122|
                    181010000001|3790000000006       |1|10000|                   |
                        |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
"""

order_detail_items = order_detail.strip().split('|')

AppSheetSerialNo = '541801030000000000237992' #申请订单号
TransactionCfmDate = '20180119' #确认日期
ConfirmedVol = '0000000000888000' #确认份额:16位，2位小数
ConfirmedAmount = '0000000000888000' #确认金额：16位，2位小数
FundCode = '021531' #产品编码，与ta对应
TransactionDate = '20180118' #交易发生日期
TransactionTime = time.strftime('%H%M%S') #交易发生时间：时分秒
ReturnCode = '0000' #交易处理返回结果码：0000代表成功
TransactionAccountID = '0106A00000108' #投资人交易基金账号
ApplicationVol = '    0000000000000000' #申请基金份数16位，前面空格不能省略，基金公司给的文件问题：赎回填此处，申购默认为0
ApplicationAmount = '0000000000888000' #申请金额：申购填此处，赎回默认为0
BusinessCode = '122'
TASerialNO = '3790000000006       ' #TA确认交易流水号:TA交易时用

# []里的下标，我是凭感觉改的，你自己核对
order_detail_items[0] = AppSheetSerialNo
order_detail_items[1] = TransactionCfmDate
#new_detail.append(list[2]) #CurrencyType结算币种
order_detail_items[3] = ConfirmedVol
order_detail_items[4] = ConfirmedAmount
order_detail_items[5] = FundCode
#new_detail.append(list[6]) #LargeRedemptionFlag巨额赎回标志
order_detail_items[7] = TransactionDate
order_detail_items[8] = TransactionTime
order_detail_items[9] = ReturnCode
order_detail_items[10] = TransactionAccountID
# new_detail.append(list[11]) #DistributorCode销售人代码,379
order_detail_items[12] = ApplicationVol
order_detail_items[13] = ApplicationAmount
order_detail_items[14] = CFM_SG


new_detail = '|'.join(order_detail_items)

print order_detail
print new_detail


'''
f = open(the_file_name.replace(".txt", "__marked.txt"), 'w')
f.write(content)
f.close()
'''    

```

**Comment by vieyahn2017** [comment]
这边 这个编辑框是markdown格式的，#跟的文字会被转换成标题行，所以你发的代码很难看
发 Python 代码，在代码前加三个数字1前面的那个反引号 `  
代码结束的后面，同样发三个反引号，代码就能高亮显示

**Comment by duli1985** [comment]
'''
#!user/bin/env Python
# -*- coding: utf-8 -*-
import re
import time
import linecache

#BusinessCode业务代码
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认

cfm_Order = 'C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT'
the_file = open(cfm_Order)
content = the_file.read()
order_detail = linecache.getline(cfm_Order, 128)

# order_detail = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|180004|0|20171128|141233|0000|0106A00000055|    379  |    0000000000000000|0000000000100000|122|181010000001|3790000000006       |1|10000|                   |    |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
"""
#方便数，每5个一行
order_detail     = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|
                    180004|0|20171128|141233|0000|
                    0106A00000055|    379  |    0000000000000000|0000000000100000|122|
                    181010000001|3790000000006       |1|10000|                   |
                        |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
"""

order_detail_items = order_detail.strip().split('|')

AppSheetSerialNo = '541801030000000000237992' #申请订单号
TransactionCfmDate = '20180119' #确认日期
ConfirmedVol = '0000000000888000' #确认份额:16位，2位小数
ConfirmedAmount = '0000000000888000' #确认金额：16位，2位小数
FundCode = '021531' #产品编码，与ta对应
TransactionDate = '20180118' #交易发生日期
TransactionTime = time.strftime('%H%M%S') #交易发生时间：时分秒
ReturnCode = '0000' #交易处理返回结果码：0000代表成功
TransactionAccountID = '0106A00000108' #投资人交易基金账号
ApplicationVol = '    0000000000000000' #申请基金份数16位，前面空格不能省略，基金公司给的文件问题：赎回填此处，申购默认为0
ApplicationAmount = '0000000000888000' #申请金额：申购填此处，赎回默认为0
TASerialNO = '3790000000006       ' #TA确认交易流水号:TA交易时用
Charge = '0000000000' #手续费:10(两位小数)
AgencyFee = '0000000000' #代理费:10（两位小数）
NAV = '0010500' #基金单位净值:7（四位小数）
DefDividendMethod = ' ' #默认分红方式
TargetNAV = '0010800' #目标基金的单位净值:7（四位小数）

# []里的下标，代表每个字段，参考文件《中登2.0开放式基金业务数据交换协议0902》7.66.4　交易确认（04文件）
order_detail_items[0] = AppSheetSerialNo
order_detail_items[1] = TransactionCfmDate
order_detail_items[3] = ConfirmedVol
order_detail_items[4] = ConfirmedAmount
order_detail_items[5] = FundCode
order_detail_items[7] = TransactionDate
order_detail_items[8] = TransactionTime
order_detail_items[9] = ReturnCode
order_detail_items[10] = TransactionAccountID
order_detail_items[12] = ApplicationVol
order_detail_items[13] = ApplicationAmount
order_detail_items[14] = CFM_SG
order_detail_items[22] = Charge
order_detail_items[23] = AgencyFee
order_detail_items[24] = NAV
order_detail_items[43] = DefDividendMethod
order_detail_items[52] = TargetNAV


new_detail = ''.join(order_detail_items)

print order_detail
print new_detail



f = open(cfm_Order.replace(".txt", "__marked.txt"), 'w')
f.write(content)
f.close()

'''

**Comment by duli1985** [comment]
```
#!user/bin/env Python
# -*- coding: utf-8 -*-
import re
import time
import linecache

#BusinessCode业务代码
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认

cfm_Order = 'C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT'
the_file = open(cfm_Order)
content = the_file.read()
order_detail = linecache.getline(cfm_Order, 128)

# order_detail = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|180004|0|20171128|141233|0000|0106A00000055|    379  |    0000000000000000|0000000000100000|122|181010000001|3790000000006       |1|10000|                   |    |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
"""
#方便数，每5个一行
order_detail     = '201711280000000002937922|20171220|156|0000000000100000|0000000000100000|
                    180004|0|20171128|141233|0000|
                    0106A00000055|    379  |    0000000000000000|0000000000100000|122|
                    181010000001|3790000000006       |1|10000|                   |
                        |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220'
"""

order_detail_items = order_detail.strip().split('|')

AppSheetSerialNo = '541801030000000000237992' #申请订单号
TransactionCfmDate = '20180119' #确认日期
ConfirmedVol = '0000000000888000' #确认份额:16位，2位小数
ConfirmedAmount = '0000000000888000' #确认金额：16位，2位小数
FundCode = '021531' #产品编码，与ta对应
TransactionDate = '20180118' #交易发生日期
TransactionTime = time.strftime('%H%M%S') #交易发生时间：时分秒
ReturnCode = '0000' #交易处理返回结果码：0000代表成功
TransactionAccountID = '0106A00000108' #投资人交易基金账号
ApplicationVol = '    0000000000000000' #申请基金份数16位，前面空格不能省略，基金公司给的文件问题：赎回填此处，申购默认为0
ApplicationAmount = '0000000000888000' #申请金额：申购填此处，赎回默认为0
TASerialNO = '3790000000006       ' #TA确认交易流水号:TA交易时用
Charge = '0000000000' #手续费:10(两位小数)
AgencyFee = '0000000000' #代理费:10（两位小数）
NAV = '0010500' #基金单位净值:7（四位小数）
DefDividendMethod = ' ' #默认分红方式
TargetNAV = '0010800' #目标基金的单位净值:7（四位小数）

# []里的下标，代表每个字段，参考文件《中登2.0开放式基金业务数据交换协议0902》7.66.4　交易确认（04文件）
order_detail_items[0] = AppSheetSerialNo
order_detail_items[1] = TransactionCfmDate
order_detail_items[3] = ConfirmedVol
order_detail_items[4] = ConfirmedAmount
order_detail_items[5] = FundCode
order_detail_items[7] = TransactionDate
order_detail_items[8] = TransactionTime
order_detail_items[9] = ReturnCode
order_detail_items[10] = TransactionAccountID
order_detail_items[12] = ApplicationVol
order_detail_items[13] = ApplicationAmount
order_detail_items[14] = CFM_SG
order_detail_items[22] = Charge
order_detail_items[23] = AgencyFee
order_detail_items[24] = NAV
order_detail_items[43] = DefDividendMethod
order_detail_items[52] = TargetNAV


new_detail = ''.join(order_detail_items)

print order_detail
print new_detail



f = open(cfm_Order.replace(".txt", "__marked.txt"), 'w')
f.write(content)
f.close()

```

**Comment by vieyahn2017** [comment]
你测试对了就好， 剩下就是写文件

**Comment by duli1985** [comment]
1.写文件，还是按照你的方法，先设置变量吗？还是能直接写入某一行啊？
2.还有一个功能，按照不同的交易类型，生成不同的数据。交易类型是这些：
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认）

**Comment by vieyahn2017** [comment]
linecache只能读

**Comment by vieyahn2017** [comment]
```python
#!/usr/bin/python
#encoding: utf-8

import re
import time

new_date = "20180109" # 你要改成的日期

#BusinessCode业务代码
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认

AppSheetSerialNo = '541801030000000000237992' #申请订单号
TransactionCfmDate = '20180119' #确认日期
ConfirmedVol = '0000000000888000' #确认份额:16位，2位小数
ConfirmedAmount = '0000000000888000' #确认金额：16位，2位小数
FundCode = '021531' #产品编码，与ta对应
TransactionDate = '20180118' #交易发生日期
TransactionTime = time.strftime('%H%M%S') #交易发生时间：时分秒
ReturnCode = '0000' #交易处理返回结果码：0000代表成功
TransactionAccountID = '0106A00000108' #投资人交易基金账号
ApplicationVol = '    0000000000000000' #申请基金份数16位，前面空格不能省略，基金公司给的文件问题：赎回填此处，申购默认为0
ApplicationAmount = '0000000000888000' #申请金额：申购填此处，赎回默认为0
TASerialNO = '3790000000006       ' #TA确认交易流水号:TA交易时用
Charge = '0000000000' #手续费:10(两位小数)
AgencyFee = '0000000000' #代理费:10（两位小数）
NAV = '0010500' #基金单位净值:7（四位小数）
DefDividendMethod = ' ' #默认分红方式
TargetNAV = '0010800' #目标基金的单位净值:7（四位小数）


def _rewrite_order_detail(order_detail):
    """按行处理"""
    print order_detail
    order_detail_items = order_detail.strip().split('|')
    order_detail_items[0] = AppSheetSerialNo
    order_detail_items[1] = TransactionCfmDate
    order_detail_items[3] = ConfirmedVol
    order_detail_items[4] = ConfirmedAmount
    order_detail_items[5] = FundCode
    order_detail_items[7] = TransactionDate
    order_detail_items[8] = TransactionTime
    order_detail_items[9] = ReturnCode
    order_detail_items[10] = TransactionAccountID
    order_detail_items[12] = ApplicationVol
    order_detail_items[13] = ApplicationAmount
    order_detail_items[14] = CFM_SG
    order_detail_items[22] = Charge
    order_detail_items[23] = AgencyFee
    order_detail_items[24] = NAV
    order_detail_items[43] = DefDividendMethod
    order_detail_items[52] = TargetNAV

    new_detail = '|'.join(order_detail_items)
    return new_detail


the_file_name = "201801080005.txt"
the_file = open(the_file_name)
content = the_file.read()

content_lines = content.strip().split('\n')
order_counts = len(content_lines) - 128
print "order counts is :", order_counts
# 如果总共是130行，第127行是条数汇总，第130行是结束，实际交易条数是2行

for i in range(order_counts):
    content_lines[127+i] = _rewrite_order_detail(content_lines[127+i])


print content_lines

f = open(the_file_name.replace(".txt", "__marked.txt"), 'w')
f.write('\n'.join(content_lines))
f.close()


```

**Comment by vieyahn2017** [comment]
写文件是上面的代码

至于 2.还有一个功能，按照不同的交易类型，生成不同的数据。交易类型是这些： 
理清了，说清了 再说

**Comment by vieyahn2017** [comment]
```python
#BusinessCode业务代码
CFM_SG = '122' #申购确认
CFM_RG = '120' #认购确认
CFM_SH = '124' #赎回确认
CFM_SZFHFS = '129' #设置分红方式确认
CFM_TZ = '144' #强行调增确认
CMF_TJ = '145' #强行调减确认
CMF_QS = '142'#强行赎回确认
 
## 大概需要每一种功能，写一个这样的方法

def _rewrite_order_detail_CFM_SH(order_detail):
    """赎回确认"""
    pass

def _rewrite_order_detail_CFM_RG(order_detail):
    """认购确认"""
    pass

def _rewrite_order_detail_CFM_SG(order_detail):
    """申购确认"""
    order_detail_items = order_detail.strip().split('|')
    order_detail_items[0] = AppSheetSerialNo
    order_detail_items[1] = TransactionCfmDate
    order_detail_items[3] = ConfirmedVol
    order_detail_items[4] = ConfirmedAmount
    order_detail_items[5] = FundCode
    order_detail_items[7] = TransactionDate
    order_detail_items[8] = TransactionTime
    order_detail_items[9] = ReturnCode
    order_detail_items[10] = TransactionAccountID
    order_detail_items[12] = ApplicationVol
    order_detail_items[13] = ApplicationAmount
    order_detail_items[14] = CFM_SG
    order_detail_items[22] = Charge
    order_detail_items[23] = AgencyFee
    order_detail_items[24] = NAV
    order_detail_items[43] = DefDividendMethod
    order_detail_items[52] = TargetNAV


# 然后主程序中 到底是调用哪个处理方法，要通过某些条件 来判断

```

**Comment by duli1985** [comment]
嗯嗯。

**Comment by duli1985** [comment]
```
order counts is : 3
201711280000000002937922|20171220|156|0000000000100000|0000000000100000|180004|0|20171128|141233|0000|0106A00000055|    379  |    0000000000000000|0000000000100000|122|181010000001|3790000000006       |1|10000|                   |    |20171220|0000000000|0000000000|0010000|379      |                        |        |0000000000|1|        |0000000000000000|00|000000000|0000000000000000|                    |                                                            |20171128|         |         |                 |    | | |0000000000000000|0000000000|0000000000000000|0000000000000000|0010000|        | |0000000000000000|0000000|0000000|0000000000000000|0000000000|0000000000000000|        |0000000000|0|0|0| | |        | |      |0000000000|     |     | |            |  |0106     |            | |                    |        |        |00|            |   | | |        | |                                        |00000| |0000000000000000|  |  |00000|      |0000000000000000|00000000|0010000|0000000000000000|0000000000000000|0000000000000000|0000000000000000| |3790000000006       |0000000000000000|0|0000000000000000|0000000000000000|0000000000000000|        |0000000000000000|0000000000000000|0000                                                        | |0000000000000000| |20171220

Traceback (most recent call last):
  File "E:/jb-py/jijin2.0/public/22.py", line 73, in <module>
    content_lines[127+i] = _rewrite_order_detail(content_lines[127+i])
  File "E:/jb-py/jijin2.0/public/22.py", line 42, in _rewrite_order_detail
    order_detail_items[1] = TransactionCfmDate
IndexError: list assignment index out of range

```

**Comment by vieyahn2017** [comment]
有异常数据，交易数据如果不是按|分割的，切不出来，就会报错。

**Comment by vieyahn2017** [comment]
如果list_a = [0,1,2,3]
执行list_a[4] = 4 就会报那个错

**Comment by duli1985** [comment]
```
the_file_name = "C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT"
the_file = open(the_file_name)
content = the_file.read()

content_lines = content.strip().split('\n')
order_counts = len(content_lines) - 128
print "order counts is :", order_counts
# 如果总共是130行，第127行是条数汇总，第130行是结束，实际交易条数是2行

for i in range(order_counts):
    content_lines[127+i] = _rewrite_order_detail(content_lines[127+i])


print content_lines

f = open(the_file_name.replace(".txt", "__marked.txt"), 'w')
f.write('\n'.join(content_lines))
f.close()
```

这几个什么意思呀？还是要去数128行有数据，然后再替换吗？
如果128行没有数据，是结束标识符，直接插入怎么写呢？
order_counts = len(content_lines) - 128   
content_lines[127+i] = _rewrite_order_detail(content_lines[127+i])
f = open(the_file_name.replace(".txt", "__marked.txt"), 'w')

**Comment by vieyahn2017** [comment]
没有交易order_counts =0
for i in range(order_counts): 里面循环次数为0
一样的，不用特别处理

**Comment by duli1985** [comment]
```
SHAREREGISTERDATE
00000000
OFDCFEND--128行是这个
```
这样的写不进去

**Comment by vieyahn2017** [comment]
是
